//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsWeb.ServiceReference208 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference208.UserLoginCheckSoap")]
    public interface UserLoginCheckSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strLocation 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WFUserSecondPwdChk", ReplyAction="*")]
        ReportsWeb.ServiceReference208.WFUserSecondPwdChkResponse WFUserSecondPwdChk(ReportsWeb.ServiceReference208.WFUserSecondPwdChkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WFUserSecondPwdChkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WFUserSecondPwdChk", Namespace="http://tempuri.org/", Order=0)]
        public ReportsWeb.ServiceReference208.WFUserSecondPwdChkRequestBody Body;
        
        public WFUserSecondPwdChkRequest() {
        }
        
        public WFUserSecondPwdChkRequest(ReportsWeb.ServiceReference208.WFUserSecondPwdChkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WFUserSecondPwdChkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strPassword;
        
        public WFUserSecondPwdChkRequestBody() {
        }
        
        public WFUserSecondPwdChkRequestBody(string strLocation, string strUser, string strPassword) {
            this.strLocation = strLocation;
            this.strUser = strUser;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WFUserSecondPwdChkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WFUserSecondPwdChkResponse", Namespace="http://tempuri.org/", Order=0)]
        public ReportsWeb.ServiceReference208.WFUserSecondPwdChkResponseBody Body;
        
        public WFUserSecondPwdChkResponse() {
        }
        
        public WFUserSecondPwdChkResponse(ReportsWeb.ServiceReference208.WFUserSecondPwdChkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WFUserSecondPwdChkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WFUserSecondPwdChkResult;
        
        public WFUserSecondPwdChkResponseBody() {
        }
        
        public WFUserSecondPwdChkResponseBody(string WFUserSecondPwdChkResult) {
            this.WFUserSecondPwdChkResult = WFUserSecondPwdChkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserLoginCheckSoapChannel : ReportsWeb.ServiceReference208.UserLoginCheckSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserLoginCheckSoapClient : System.ServiceModel.ClientBase<ReportsWeb.ServiceReference208.UserLoginCheckSoap>, ReportsWeb.ServiceReference208.UserLoginCheckSoap {
        
        public UserLoginCheckSoapClient() {
        }
        
        public UserLoginCheckSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserLoginCheckSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserLoginCheckSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserLoginCheckSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportsWeb.ServiceReference208.WFUserSecondPwdChkResponse ReportsWeb.ServiceReference208.UserLoginCheckSoap.WFUserSecondPwdChk(ReportsWeb.ServiceReference208.WFUserSecondPwdChkRequest request) {
            return base.Channel.WFUserSecondPwdChk(request);
        }
        
        public string WFUserSecondPwdChk(string strLocation, string strUser, string strPassword) {
            ReportsWeb.ServiceReference208.WFUserSecondPwdChkRequest inValue = new ReportsWeb.ServiceReference208.WFUserSecondPwdChkRequest();
            inValue.Body = new ReportsWeb.ServiceReference208.WFUserSecondPwdChkRequestBody();
            inValue.Body.strLocation = strLocation;
            inValue.Body.strUser = strUser;
            inValue.Body.strPassword = strPassword;
            ReportsWeb.ServiceReference208.WFUserSecondPwdChkResponse retVal = ((ReportsWeb.ServiceReference208.UserLoginCheckSoap)(this)).WFUserSecondPwdChk(inValue);
            return retVal.Body.WFUserSecondPwdChkResult;
        }
    }
}
