declare @xmldoc xml
set @xmldoc = N'<?xml version="1.0" encoding="utf-16"?>
<Report xmlns:rd="http://schemas.microsoft.com/SQLServer/reporting/reportdesigner" xmlns="http://schemas.microsoft.com/sqlserver/reporting/2008/01/reportdefinition">
  <DataSources>
    <DataSource Name="siv_mstr">
      <ConnectionProperties>
        <DataProvider>System.Data.DataSet</DataProvider>
        <ConnectString>/* Local Connection */</ConnectString>
      </ConnectionProperties>
      <rd:DataSourceID>9bea6efc-880b-4f09-b7f0-966a542c36af</rd:DataSourceID>
    </DataSource>
  </DataSources>
  <DataSets>
    <DataSet Name="rsystem">
      <Fields>
        <Field Name="Id">
          <DataField>Id</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="sysname">
          <DataField>sysname</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="sysdesczh">
          <DataField>sysdesczh</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="sysdescen">
          <DataField>sysdescen</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="sysaddr1">
          <DataField>sysaddr1</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="sysaddr2">
          <DataField>sysaddr2</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="systel">
          <DataField>systel</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="syschar1">
          <DataField>syschar1</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="doctype">
          <DataField>doctype</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="docdesc">
          <DataField>docdesc</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
      </Fields>
      <Query>
        <DataSourceName>siv_mstr</DataSourceName>
        <CommandText>/* Local Query */</CommandText>
      </Query>
      <rd:DataSetInfo>
        <rd:DataSetName>WebReportDataSet</rd:DataSetName>
        <rd:SchemaPath>D:\0ling.xie\0reports\ReportsWeb\ReportsWeb\WebReportDataSet.xsd</rd:SchemaPath>
        <rd:TableName>rsystem</rd:TableName>
        <rd:TableAdapterFillMethod>Fill</rd:TableAdapterFillMethod>
        <rd:TableAdapterGetDataMethod>GetData</rd:TableAdapterGetDataMethod>
        <rd:TableAdapterName>rsystemTableAdapter</rd:TableAdapterName>
      </rd:DataSetInfo>
    </DataSet>
    <DataSet Name="user_hw">
      <Fields>
        <Field Name="s_type">
          <DataField>s_type</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="s_desc">
          <DataField>s_desc</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="s_id">
          <DataField>s_id</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="s_time">
          <DataField>s_time</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="ip">
          <DataField>ip</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="name">
          <DataField>name</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="domain">
          <DataField>domain</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="s_mac">
          <DataField>s_mac</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="mid">
          <DataField>mid</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
      </Fields>
      <Query>
        <DataSourceName>siv_mstr</DataSourceName>
        <CommandText>/* Local Query */</CommandText>
      </Query>
      <rd:DataSetInfo>
        <rd:DataSetName>WebReportDataSet</rd:DataSetName>
        <rd:SchemaPath>D:\0ling.xie\0reports\ReportsWeb\ReportsWeb\WebReportDataSet.xsd</rd:SchemaPath>
        <rd:TableName>user_hw</rd:TableName>
        <rd:TableAdapterFillMethod />
        <rd:TableAdapterGetDataMethod />
        <rd:TableAdapterName />
      </rd:DataSetInfo>
    </DataSet>
    <DataSet Name="user_softs">
      <Fields>
        <Field Name="s_name">
          <DataField>s_name</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="s_time">
          <DataField>s_time</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="ip">
          <DataField>ip</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="name">
          <DataField>name</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="domain">
          <DataField>domain</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="osver">
          <DataField>osver</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="mid">
          <DataField>mid</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
      </Fields>
      <Query>
        <DataSourceName>siv_mstr</DataSourceName>
        <CommandText>/* Local Query */</CommandText>
      </Query>
      <rd:DataSetInfo>
        <rd:DataSetName>WebReportDataSet</rd:DataSetName>
        <rd:SchemaPath>D:\0ling.xie\0reports\ReportsWeb\ReportsWeb\WebReportDataSet.xsd</rd:SchemaPath>
        <rd:TableName>user_softs</rd:TableName>
        <rd:TableAdapterFillMethod />
        <rd:TableAdapterGetDataMethod />
        <rd:TableAdapterName />
      </rd:DataSetInfo>
    </DataSet>
  </DataSets>
  <Body>
    <ReportItems>
      <Tablix Name="Tablix2">
        <TablixBody>
          <TablixColumns>
            <TablixColumn>
              <Width>0.22797in</Width>
            </TablixColumn>
            <TablixColumn>
              <Width>1.28757in</Width>
            </TablixColumn>
            <TablixColumn>
              <Width>3.77053in</Width>
            </TablixColumn>
            <TablixColumn>
              <Width>2.50819in</Width>
            </TablixColumn>
          </TablixColumns>
          <TablixRows>
            <TablixRow>
              <Height>0.19685in</Height>
              <TablixCells>
                <TablixCell>
                  <CellContents>
                    <Textbox Name="Textbox469">
                      <CanGrow>true</CanGrow>
                      <KeepTogether>true</KeepTogether>
                      <Paragraphs>
                        <Paragraph>
                          <TextRuns>
                            <TextRun>
                              <Value />
                              <Style>
                                <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                                <FontSize>9pt</FontSize>
                                <FontWeight>Bold</FontWeight>
                              </Style>
                            </TextRun>
                          </TextRuns>
                          <Style>
                            <TextAlign>Center</TextAlign>
                          </Style>
                        </Paragraph>
                      </Paragraphs>
                      <rd:DefaultName>Textbox469</rd:DefaultName>
                      <Style>
                        <Border>
                          <Style>None</Style>
                        </Border>
                        <TopBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>1.25pt</Width>
                        </TopBorder>
                        <LeftBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>1.25pt</Width>
                        </LeftBorder>
                        <RightBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </RightBorder>
                        <VerticalAlign>Bottom</VerticalAlign>
                        <PaddingLeft>2pt</PaddingLeft>
                        <PaddingRight>2pt</PaddingRight>
                        <PaddingTop>2pt</PaddingTop>
                        <PaddingBottom>2pt</PaddingBottom>
                      </Style>
                    </Textbox>
                  </CellContents>
                </TablixCell>
                <TablixCell>
                  <CellContents>
                    <Textbox Name="Textbox1">
                      <CanGrow>true</CanGrow>
                      <KeepTogether>true</KeepTogether>
                      <Paragraphs>
                        <Paragraph>
                          <TextRuns>
                            <TextRun>
                              <Value>Ó²¼þÀàÐÍ</Value>
                              <Style>
                                <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                                <FontSize>9pt</FontSize>
                                <FontWeight>Bold</FontWeight>
                              </Style>
                            </TextRun>
                          </TextRuns>
                          <Style>
                            <TextAlign>Center</TextAlign>
                          </Style>
                        </Paragraph>
                      </Paragraphs>
                      <rd:DefaultName>Textbox1</rd:DefaultName>
                      <Style>
                        <Border>
                          <Style>None</Style>
                        </Border>
                        <TopBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>1.25pt</Width>
                        </TopBorder>
                        <RightBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </RightBorder>
                        <VerticalAlign>Bottom</VerticalAlign>
                        <PaddingLeft>2pt</PaddingLeft>
                        <PaddingRight>2pt</PaddingRight>
                        <PaddingTop>2pt</PaddingTop>
                        <PaddingBottom>2pt</PaddingBottom>
                      </Style>
                    </Textbox>
                  </CellContents>
                </TablixCell>
                <TablixCell>
                  <CellContents>
                    <Textbox Name="Textbox2">
                      <CanGrow>true</CanGrow>
                      <KeepTogether>true</KeepTogether>
                      <Paragraphs>
                        <Paragraph>
                          <TextRuns>
                            <TextRun>
                              <Value>Ó²¼þÃèÊö</Value>
                              <Style>
                                <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                                <FontSize>9pt</FontSize>
                                <FontWeight>Bold</FontWeight>
                              </Style>
                            </TextRun>
                          </TextRuns>
                          <Style>
                            <TextAlign>Center</TextAlign>
                          </Style>
                        </Paragraph>
                      </Paragraphs>
                      <rd:DefaultName>Textbox2</rd:DefaultName>
                      <Style>
                        <Border>
                          <Style>None</Style>
                        </Border>
                        <TopBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>1.25pt</Width>
                        </TopBorder>
                        <RightBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </RightBorder>
                        <VerticalAlign>Bottom</VerticalAlign>
                        <PaddingLeft>2pt</PaddingLeft>
                        <PaddingRight>2pt</PaddingRight>
                        <PaddingTop>2pt</PaddingTop>
                        <PaddingBottom>2pt</PaddingBottom>
                      </Style>
                    </Textbox>
                  </CellContents>
                </TablixCell>
                <TablixCell>
                  <CellContents>
                    <Textbox Name="Textbox3">
                      <CanGrow>true</CanGrow>
                      <KeepTogether>true</KeepTogether>
                      <Paragraphs>
                        <Paragraph>
                          <TextRuns>
                            <TextRun>
                              <Value>Ó²¼þ£É£Ä</Value>
                              <Style>
                                <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                                <FontSize>9pt</FontSize>
                                <FontWeight>Bold</FontWeight>
                              </Style>
                            </TextRun>
                          </TextRuns>
                          <Style>
                            <TextAlign>Center</TextAlign>
                          </Style>
                        </Paragraph>
                      </Paragraphs>
                      <rd:DefaultName>Textbox3</rd:DefaultName>
                      <Style>
                        <Border>
                          <Style>None</Style>
                        </Border>
                        <TopBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>1.25pt</Width>
                        </TopBorder>
                        <RightBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </RightBorder>
                        <VerticalAlign>Bottom</VerticalAlign>
                        <PaddingLeft>2pt</PaddingLeft>
                        <PaddingRight>2pt</PaddingRight>
                        <PaddingTop>2pt</PaddingTop>
                        <PaddingBottom>2pt</PaddingBottom>
                      </Style>
                    </Textbox>
                  </CellContents>
                </TablixCell>
              </TablixCells>
            </TablixRow>
            <TablixRow>
              <Height>0.18898in</Height>
              <TablixCells>
                <TablixCell>
                  <CellContents>
                    <Textbox Name="Textbox470">
                      <CanGrow>true</CanGrow>
                      <KeepTogether>true</KeepTogether>
                      <Paragraphs>
                        <Paragraph>
                          <TextRuns>
                            <TextRun>
                              <Value>=rownumber(Nothing)</Value>
                              <Style>
                                <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                                <FontSize>8pt</FontSize>
                              </Style>
                            </TextRun>
                          </TextRuns>
                          <Style>
                            <TextAlign>Left</TextAlign>
                          </Style>
                        </Paragraph>
                      </Paragraphs>
                      <rd:DefaultName>Textbox470</rd:DefaultName>
                      <Style>
                        <Border>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </Border>
                        <TopBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </TopBorder>
                        <BottomBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </BottomBorder>
                        <LeftBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>1.25pt</Width>
                        </LeftBorder>
                        <RightBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </RightBorder>
                        <VerticalAlign>Middle</VerticalAlign>
                        <PaddingLeft>2pt</PaddingLeft>
                        <PaddingRight>2pt</PaddingRight>
                        <PaddingTop>2pt</PaddingTop>
                        <PaddingBottom>2pt</PaddingBottom>
                      </Style>
                    </Textbox>
                  </CellContents>
                </TablixCell>
                <TablixCell>
                  <CellContents>
                    <Textbox Name="s_type">
                      <CanGrow>true</CanGrow>
                      <KeepTogether>true</KeepTogether>
                      <Paragraphs>
                        <Paragraph>
                          <TextRuns>
                            <TextRun>
                              <Value>=Fields!s_type.Value</Value>
                              <Style>
                                <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                                <FontSize>8pt</FontSize>
                              </Style>
                            </TextRun>
                          </TextRuns>
                          <Style>
                            <TextAlign>Left</TextAlign>
                          </Style>
                        </Paragraph>
                      </Paragraphs>
                      <rd:DefaultName>s_type</rd:DefaultName>
                      <Style>
                        <Border>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </Border>
                        <VerticalAlign>Middle</VerticalAlign>
                        <PaddingLeft>2pt</PaddingLeft>
                        <PaddingRight>2pt</PaddingRight>
                        <PaddingTop>2pt</PaddingTop>
                        <PaddingBottom>2pt</PaddingBottom>
                      </Style>
                    </Textbox>
                  </CellContents>
                </TablixCell>
                <TablixCell>
                  <CellContents>
                    <Textbox Name="s_desc">
                      <CanGrow>true</CanGrow>
                      <KeepTogether>true</KeepTogether>
                      <Paragraphs>
                        <Paragraph>
                          <TextRuns>
                            <TextRun>
                              <Value>=Fields!s_desc.Value</Value>
                              <Style>
                                <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                                <FontSize>8pt</FontSize>
                              </Style>
                            </TextRun>
                          </TextRuns>
                          <Style>
                            <TextAlign>Left</TextAlign>
                          </Style>
                        </Paragraph>
                      </Paragraphs>
                      <rd:DefaultName>s_desc</rd:DefaultName>
                      <Style>
                        <Border>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </Border>
                        <TopBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </TopBorder>
                        <BottomBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </BottomBorder>
                        <LeftBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </LeftBorder>
                        <RightBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </RightBorder>
                        <VerticalAlign>Middle</VerticalAlign>
                        <PaddingLeft>2pt</PaddingLeft>
                        <PaddingRight>2pt</PaddingRight>
                        <PaddingTop>2pt</PaddingTop>
                        <PaddingBottom>2pt</PaddingBottom>
                      </Style>
                    </Textbox>
                  </CellContents>
                </TablixCell>
                <TablixCell>
                  <CellContents>
                    <Textbox Name="s_id">
                      <CanGrow>true</CanGrow>
                      <KeepTogether>true</KeepTogether>
                      <Paragraphs>
                        <Paragraph>
                          <TextRuns>
                            <TextRun>
                              <Value>=Fields!s_id.Value</Value>
                              <Style>
                                <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                                <FontSize>8pt</FontSize>
                              </Style>
                            </TextRun>
                          </TextRuns>
                          <Style>
                            <TextAlign>Left</TextAlign>
                          </Style>
                        </Paragraph>
                      </Paragraphs>
                      <rd:DefaultName>s_id</rd:DefaultName>
                      <Style>
                        <Border>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </Border>
                        <TopBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </TopBorder>
                        <BottomBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </BottomBorder>
                        <LeftBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </LeftBorder>
                        <RightBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </RightBorder>
                        <PaddingLeft>2pt</PaddingLeft>
                        <PaddingRight>2pt</PaddingRight>
                        <PaddingTop>2pt</PaddingTop>
                        <PaddingBottom>2pt</PaddingBottom>
                      </Style>
                    </Textbox>
                  </CellContents>
                </TablixCell>
              </TablixCells>
            </TablixRow>
          </TablixRows>
        </TablixBody>
        <TablixColumnHierarchy>
          <TablixMembers>
            <TablixMember />
            <TablixMember />
            <TablixMember />
            <TablixMember />
          </TablixMembers>
        </TablixColumnHierarchy>
        <TablixRowHierarchy>
          <TablixMembers>
            <TablixMember>
              <KeepWithGroup>After</KeepWithGroup>
              <RepeatOnNewPage>true</RepeatOnNewPage>
              <KeepTogether>true</KeepTogether>
            </TablixMember>
            <TablixMember>
              <Group Name="ÏêÏ¸ÐÅÏ¢1" />
            </TablixMember>
          </TablixMembers>
        </TablixRowHierarchy>
        <DataSetName>user_hw</DataSetName>
        <Top>0.54709cm</Top>
        <Left>0.25017cm</Left>
        <Height>0.98cm</Height>
        <Width>19.79742cm</Width>
        <Style>
          <Border>
            <Style>None</Style>
          </Border>
        </Style>
      </Tablix>
      <Tablix Name="Tablix3">
        <TablixBody>
          <TablixColumns>
            <TablixColumn>
              <Width>0.37929in</Width>
            </TablixColumn>
            <TablixColumn>
              <Width>7.41421in</Width>
            </TablixColumn>
          </TablixColumns>
          <TablixRows>
            <TablixRow>
              <Height>0.19685in</Height>
              <TablixCells>
                <TablixCell>
                  <CellContents>
                    <Textbox Name="Textbox471">
                      <CanGrow>true</CanGrow>
                      <KeepTogether>true</KeepTogether>
                      <Paragraphs>
                        <Paragraph>
                          <TextRuns>
                            <TextRun>
                              <Value />
                              <Style>
                                <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                                <FontSize>9pt</FontSize>
                                <FontWeight>Bold</FontWeight>
                              </Style>
                            </TextRun>
                          </TextRuns>
                          <Style>
                            <TextAlign>Center</TextAlign>
                          </Style>
                        </Paragraph>
                      </Paragraphs>
                      <rd:DefaultName>Textbox469</rd:DefaultName>
                      <Style>
                        <Border>
                          <Style>None</Style>
                        </Border>
                        <TopBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>1.25pt</Width>
                        </TopBorder>
                        <LeftBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>1.25pt</Width>
                        </LeftBorder>
                        <RightBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </RightBorder>
                        <VerticalAlign>Bottom</VerticalAlign>
                        <PaddingLeft>2pt</PaddingLeft>
                        <PaddingRight>2pt</PaddingRight>
                        <PaddingTop>2pt</PaddingTop>
                        <PaddingBottom>2pt</PaddingBottom>
                      </Style>
                    </Textbox>
                  </CellContents>
                </TablixCell>
                <TablixCell>
                  <CellContents>
                    <Textbox Name="Textbox27">
                      <CanGrow>true</CanGrow>
                      <KeepTogether>true</KeepTogether>
                      <Paragraphs>
                        <Paragraph>
                          <TextRuns>
                            <TextRun>
                              <Value>Èí¼þÃû³Æ</Value>
                              <Style>
                                <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                                <FontSize>9pt</FontSize>
                                <FontWeight>Bold</FontWeight>
                              </Style>
                            </TextRun>
                          </TextRuns>
                          <Style>
                            <TextAlign>Center</TextAlign>
                          </Style>
                        </Paragraph>
                      </Paragraphs>
                      <rd:DefaultName>Textbox27</rd:DefaultName>
                      <Style>
                        <Border>
                          <Style>None</Style>
                        </Border>
                        <TopBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>1.25pt</Width>
                        </TopBorder>
                        <RightBorder>
                          <Color>Black</Color>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </RightBorder>
                        <VerticalAlign>Bottom</VerticalAlign>
                        <PaddingLeft>2pt</PaddingLeft>
                        <PaddingRight>2pt</PaddingRight>
                        <PaddingTop>2pt</PaddingTop>
                        <PaddingBottom>2pt</PaddingBottom>
                      </Style>
                    </Textbox>
                  </CellContents>
                </TablixCell>
              </TablixCells>
            </TablixRow>
            <TablixRow>
              <Height>0.17717in</Height>
              <TablixCells>
                <TablixCell>
                  <CellContents>
                    <Textbox Name="Textbox472">
                      <CanGrow>true</CanGrow>
                      <KeepTogether>true</KeepTogether>
                      <Paragraphs>
                        <Paragraph>
                          <TextRuns>
                            <TextRun>
                              <Value>=rownumber(Nothing)</Value>
                              <Style>
                                <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                                <FontSize>8pt</FontSize>
                              </Style>
                            </TextRun>
                          </TextRuns>
                          <Style>
                            <TextAlign>Center</TextAlign>
                          </Style>
                        </Paragraph>
                      </Paragraphs>
                      <rd:DefaultName>Textbox470</rd:DefaultName>
                      <Style>
                        <Border>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </Border>
                        <LeftBorder>
                          <Width>1.25pt</Width>
                        </LeftBorder>
                        <VerticalAlign>Middle</VerticalAlign>
                        <PaddingLeft>2pt</PaddingLeft>
                        <PaddingRight>2pt</PaddingRight>
                      </Style>
                    </Textbox>
                  </CellContents>
                </TablixCell>
                <TablixCell>
                  <CellContents>
                    <Textbox Name="s_type2">
                      <CanGrow>true</CanGrow>
                      <KeepTogether>true</KeepTogether>
                      <Paragraphs>
                        <Paragraph>
                          <TextRuns>
                            <TextRun>
                              <Value>=Fields!s_name.Value</Value>
                              <Style>
                                <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                                <FontSize>8pt</FontSize>
                              </Style>
                            </TextRun>
                          </TextRuns>
                          <Style>
                            <TextAlign>Left</TextAlign>
                          </Style>
                        </Paragraph>
                      </Paragraphs>
                      <rd:DefaultName>s_type</rd:DefaultName>
                      <Style>
                        <Border>
                          <Style>Solid</Style>
                          <Width>0.5pt</Width>
                        </Border>
                        <VerticalAlign>Middle</VerticalAlign>
                        <PaddingLeft>2pt</PaddingLeft>
                        <PaddingRight>2pt</PaddingRight>
                      </Style>
                    </Textbox>
                  </CellContents>
                </TablixCell>
              </TablixCells>
            </TablixRow>
          </TablixRows>
        </TablixBody>
        <TablixColumnHierarchy>
          <TablixMembers>
            <TablixMember />
            <TablixMember />
          </TablixMembers>
        </TablixColumnHierarchy>
        <TablixRowHierarchy>
          <TablixMembers>
            <TablixMember>
              <KeepWithGroup>After</KeepWithGroup>
              <RepeatOnNewPage>true</RepeatOnNewPage>
              <KeepTogether>true</KeepTogether>
            </TablixMember>
            <TablixMember>
              <Group Name="ÏêÏ¸ÐÅÏ¢2" />
            </TablixMember>
          </TablixMembers>
        </TablixRowHierarchy>
        <DataSetName>user_softs</DataSetName>
        <Top>2.07417cm</Top>
        <Left>0.25017cm</Left>
        <Height>0.95cm</Height>
        <Width>19.79549cm</Width>
        <ZIndex>1</ZIndex>
        <Style>
          <Border>
            <Style>None</Style>
          </Border>
        </Style>
      </Tablix>
      <Textbox Name="Textbox34">
        <CanGrow>true</CanGrow>
        <KeepTogether>true</KeepTogether>
        <Paragraphs>
          <Paragraph>
            <TextRuns>
              <TextRun>
                <Value>°²×°Èí¼þÃ÷Ï¸</Value>
                <Style>
                  <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  <FontWeight>Bold</FontWeight>
                  <TextDecoration>Underline</TextDecoration>
                </Style>
              </TextRun>
            </TextRuns>
            <Style>
              <TextAlign>Left</TextAlign>
            </Style>
          </Paragraph>
        </Paragraphs>
        <rd:DefaultName>Textbox34</rd:DefaultName>
        <Top>1.52709cm</Top>
        <Left>0.26327cm</Left>
        <Height>0.54709cm</Height>
        <Width>2.71148cm</Width>
        <ZIndex>2</ZIndex>
        <Style>
          <Border>
            <Style>None</Style>
          </Border>
          <PaddingLeft>2pt</PaddingLeft>
          <PaddingRight>2pt</PaddingRight>
        </Style>
      </Textbox>
      <Textbox Name="Textbox35">
        <CanGrow>true</CanGrow>
        <KeepTogether>true</KeepTogether>
        <Paragraphs>
          <Paragraph>
            <TextRuns>
              <TextRun>
                <Value>ÏµÍ³Ó²¼þÃ÷Ï¸</Value>
                <Style>
                  <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  <FontWeight>Bold</FontWeight>
                  <TextDecoration>Underline</TextDecoration>
                </Style>
              </TextRun>
            </TextRuns>
            <Style>
              <TextAlign>Left</TextAlign>
            </Style>
          </Paragraph>
        </Paragraphs>
        <rd:DefaultName>Textbox34</rd:DefaultName>
        <Left>0.26327cm</Left>
        <Height>0.54709cm</Height>
        <Width>2.71148cm</Width>
        <ZIndex>3</ZIndex>
        <Style>
          <Border>
            <Style>None</Style>
          </Border>
          <VerticalAlign>Middle</VerticalAlign>
          <PaddingLeft>2pt</PaddingLeft>
          <PaddingRight>2pt</PaddingRight>
        </Style>
      </Textbox>
      <Textbox Name="Textbox65">
        <CanGrow>true</CanGrow>
        <KeepTogether>true</KeepTogether>
        <Paragraphs>
          <Paragraph>
            <TextRuns>
              <TextRun>
                <Value>SMID:</Value>
                <Style>
                  <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                </Style>
              </TextRun>
            </TextRuns>
            <Style>
              <TextAlign>Right</TextAlign>
            </Style>
          </Paragraph>
        </Paragraphs>
        <rd:DefaultName>Textbox51</rd:DefaultName>
        <Left>6.19284cm</Left>
        <Height>0.54709cm</Height>
        <Width>2.35889cm</Width>
        <ZIndex>4</ZIndex>
        <Style>
          <Border>
            <Style>None</Style>
          </Border>
          <VerticalAlign>Middle</VerticalAlign>
          <PaddingLeft>2pt</PaddingLeft>
          <PaddingRight>2pt</PaddingRight>
        </Style>
      </Textbox>
      <Textbox Name="mid">
        <CanGrow>true</CanGrow>
        <KeepTogether>true</KeepTogether>
        <Paragraphs>
          <Paragraph>
            <TextRuns>
              <TextRun>
                <Value>=First(Fields!mid.Value, "user_hw")</Value>
                <Style />
              </TextRun>
            </TextRuns>
            <Style>
              <TextAlign>Left</TextAlign>
            </Style>
          </Paragraph>
        </Paragraphs>
        <rd:DefaultName>mid</rd:DefaultName>
        <Left>8.55173cm</Left>
        <Height>0.54709cm</Height>
        <Width>11.49393cm</Width>
        <ZIndex>5</ZIndex>
        <Style>
          <Border>
            <Style>None</Style>
          </Border>
          <VerticalAlign>Middle</VerticalAlign>
          <PaddingLeft>2pt</PaddingLeft>
          <PaddingRight>2pt</PaddingRight>
          <PaddingTop>2pt</PaddingTop>
        </Style>
      </Textbox>
    </ReportItems>
    <Height>1.23055in</Height>
    <Style />
  </Body>
  <ReportParameters>
    <ReportParameter Name="bk">
      <DataType>String</DataType>
      <DefaultValue>
        <Values>
          <Value>main</Value>
        </Values>
      </DefaultValue>
      <AllowBlank>true</AllowBlank>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
    <ReportParameter Name="logo">
      <DataType>String</DataType>
      <DefaultValue>
        <Values>
          <Value>logo</Value>
        </Values>
      </DefaultValue>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
    <ReportParameter Name="cust_siv_amt_desc">
      <DataType>String</DataType>
      <DefaultValue>
        <Values>
          <Value>xlgwr</Value>
        </Values>
      </DefaultValue>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
    <ReportParameter Name="sysname">
      <DataType>String</DataType>
      <DefaultValue>
        <Values>
          <Value>WEC</Value>
        </Values>
      </DefaultValue>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
    <ReportParameter Name="seal">
      <DataType>String</DataType>
      <DefaultValue>
        <Values>
          <Value>£Îothing</Value>
        </Values>
      </DefaultValue>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
  </ReportParameters>
  <Code> Public Shared Function ToFirstA(ByVal content As String, ByVal start As Long, ByVal replace As Char)
        Dim a, b, i, c, d, temp
        temp = ""
        a = content.Replace(replace, " ")
        b = Len(content)
        d = 1
        For i = 1 To b
            c = Mid(a, i, 1)

            If ((Asc(c) &gt; 96 And Asc(c) &lt; 123) Or (Asc(c) &gt; 64 And Asc(c) &lt; 91)) Then
                If d = 1 Then
                    temp = temp &amp; UCase(c)
                    d = 0
                Else
                    temp = temp &amp; LCase(c)
                End If
            Else
                temp = temp &amp; LCase(c)
                d = 1
            End If
        Next
        Return temp
End Function
</Code>
  <Width>7.97817in</Width>
  <Page>
    <PageHeader>
      <Height>3.26382cm</Height>
      <PrintOnFirstPage>true</PrintOnFirstPage>
      <PrintOnLastPage>true</PrintOnLastPage>
      <ReportItems>
        <Textbox Name="Textbox6">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>=First(Fields!sysdescen.Value, "rsystem") &amp; vbcrlf &amp; First(Fields!sysdesczh.Value, "rsystem")</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                    <FontSize>11pt</FontSize>
                    <FontWeight>Bold</FontWeight>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox4</rd:DefaultName>
          <Top>0.15875cm</Top>
          <Left>1.71728cm</Left>
          <Height>1.2cm</Height>
          <Width>11.40197cm</Width>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <VerticalAlign>Middle</VerticalAlign>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Image Name="Image1">
          <Source>Embedded</Source>
          <Value>=Switch(Parameters!logo.Value = "logo","logo")</Value>
          <Sizing>FitProportional</Sizing>
          <Top>0.15875cm</Top>
          <Left>0.23152cm</Left>
          <Height>1.2cm</Height>
          <Width>1.48576cm</Width>
          <ZIndex>1</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
          </Style>
        </Image>
        <Textbox Name="ip">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>=First(Fields!ip.Value, "user_hw")</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>ip</rd:DefaultName>
          <Top>0.75875cm</Top>
          <Left>15.48008cm</Left>
          <Height>0.6cm</Height>
          <Width>4.56752cm</Width>
          <ZIndex>2</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="name">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>=First(Fields!name.Value, "user_hw")</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>name</rd:DefaultName>
          <Top>0.15875cm</Top>
          <Left>15.48008cm</Left>
          <Height>0.6cm</Height>
          <Width>4.56752cm</Width>
          <ZIndex>3</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox51">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>IP:</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Right</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>0.75875cm</Top>
          <Left>13.12119cm</Left>
          <Height>0.6cm</Height>
          <Width>2.35889cm</Width>
          <ZIndex>4</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox52">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>µçÄÔÃû:</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Right</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>0.15875cm</Top>
          <Left>13.12119cm</Left>
          <Height>0.6cm</Height>
          <Width>2.35889cm</Width>
          <ZIndex>5</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox53">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>²Ù×÷ÏµÍ³:</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Right</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>1.95875cm</Top>
          <Left>13.12119cm</Left>
          <Height>0.6cm</Height>
          <Width>2.35889cm</Width>
          <ZIndex>6</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox54">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>Óò:</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Right</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>1.35875cm</Top>
          <Left>13.12119cm</Left>
          <Height>0.6cm</Height>
          <Width>2.35889cm</Width>
          <ZIndex>7</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="domain">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>=First(Fields!domain.Value, "user_hw")</Value>
                  <Style />
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>domain</rd:DefaultName>
          <Top>1.35875cm</Top>
          <Left>15.48008cm</Left>
          <Height>0.6cm</Height>
          <Width>4.56752cm</Width>
          <ZIndex>8</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="osver">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>=First(Fields!osver.Value, "user_softs")</Value>
                  <Style />
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>osver</rd:DefaultName>
          <Top>1.95875cm</Top>
          <Left>15.48008cm</Left>
          <Height>0.6cm</Height>
          <Width>4.56752cm</Width>
          <ZIndex>9</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox55">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>É¨ÃèÊ±¼ä:</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Right</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>2.55875cm</Top>
          <Left>13.11926cm</Left>
          <Height>0.6cm</Height>
          <Width>2.35889cm</Width>
          <ZIndex>10</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="s_time">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>=First(Fields!s_time.Value, "user_softs")</Value>
                  <Style />
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>s_time</rd:DefaultName>
          <Top>2.55875cm</Top>
          <Left>15.47815cm</Left>
          <Height>0.6cm</Height>
          <Width>4.56752cm</Width>
          <ZIndex>11</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox56">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>ÓÃ»§Ãû:</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Right</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>1.35875cm</Top>
          <Left>0.23152cm</Left>
          <Height>0.6cm</Height>
          <Width>1.48576cm</Width>
          <ZIndex>12</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox57">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>¹¤ºÅ:</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Right</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>1.95875cm</Top>
          <Left>0.23152cm</Left>
          <Height>0.6cm</Height>
          <Width>1.48576cm</Width>
          <ZIndex>13</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox58">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>Â¥²ã£¯Î»ÖÃ:</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Right</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>1.95875cm</Top>
          <Left>6.19284cm</Left>
          <Height>0.6cm</Height>
          <Width>2.35889cm</Width>
          <ZIndex>14</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox59">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>Àà±ð:</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Right</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>1.35875cm</Top>
          <Left>6.19284cm</Left>
          <Height>0.6cm</Height>
          <Width>2.35889cm</Width>
          <ZIndex>15</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox60">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value />
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>1.35875cm</Top>
          <Left>1.71728cm</Left>
          <Height>0.6cm</Height>
          <Width>4.47556cm</Width>
          <ZIndex>16</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <BottomBorder>
              <Color>Black</Color>
              <Style>Solid</Style>
              <Width>1pt</Width>
            </BottomBorder>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox61">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value />
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>1.95875cm</Top>
          <Left>1.71728cm</Left>
          <Height>0.6cm</Height>
          <Width>4.47556cm</Width>
          <ZIndex>17</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <BottomBorder>
              <Color>Black</Color>
              <Style>Solid</Style>
              <Width>1pt</Width>
            </BottomBorder>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox62">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value />
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>1.95875cm</Top>
          <Left>8.55173cm</Left>
          <Height>0.6cm</Height>
          <Width>4.56752cm</Width>
          <ZIndex>18</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <BottomBorder>
              <Color>Black</Color>
              <Style>Solid</Style>
              <Width>1pt</Width>
            </BottomBorder>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox63">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>°ì¹«ÊÒ£¯Éú²úÏß£¯²âÊÔ»ú</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>1.35875cm</Top>
          <Left>8.55173cm</Left>
          <Height>0.6cm</Height>
          <Width>4.56752cm</Width>
          <ZIndex>19</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <BottomBorder>
              <Color>Black</Color>
              <Style>Solid</Style>
              <Width>1pt</Width>
            </BottomBorder>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox64">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>MACµØÖ·:</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Right</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>2.55875cm</Top>
          <Left>6.19284cm</Left>
          <Height>0.6cm</Height>
          <Width>2.35889cm</Width>
          <ZIndex>20</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="s_time2">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>=UCase(left(First(Fields!s_mac.Value, "user_hw"),4) &amp; ":" &amp; Mid(First(Fields!s_mac.Value, "user_hw"),5,4) &amp; ":" &amp; right(First(Fields!s_mac.Value, "user_hw"),4))</Value>
                  <Style />
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>s_time</rd:DefaultName>
          <Top>2.55875cm</Top>
          <Left>8.55173cm</Left>
          <Height>0.6cm</Height>
          <Width>4.56752cm</Width>
          <ZIndex>21</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <VerticalAlign>Middle</VerticalAlign>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
          </Style>
        </Textbox>
        <Textbox Name="Textbox66">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>²¿ÃÅ:</Value>
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Right</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>2.60191cm</Top>
          <Left>0.23152cm</Left>
          <Height>0.6cm</Height>
          <Width>1.48576cm</Width>
          <ZIndex>22</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox67">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value />
                  <Style>
                    <FontFamily>Î¢ÈíÑÅºÚ</FontFamily>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox51</rd:DefaultName>
          <Top>2.60191cm</Top>
          <Left>1.71728cm</Left>
          <Height>0.6cm</Height>
          <Width>4.47556cm</Width>
          <ZIndex>23</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <BottomBorder>
              <Color>Black</Color>
              <Style>Solid</Style>
              <Width>1pt</Width>
            </BottomBorder>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
      </ReportItems>
      <Style>
        <Border>
          <Style>None</Style>
        </Border>
      </Style>
    </PageHeader>
    <PageFooter>
      <Height>0.80933cm</Height>
      <PrintOnFirstPage>true</PrintOnFirstPage>
      <PrintOnLastPage>true</PrintOnLastPage>
      <ReportItems>
        <Textbox Name="Textbox335">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>="Pages: " + cstr(Globals!PageNumber) + "/" + CSTR(Globals!TotalPages)</Value>
                  <Style>
                    <FontWeight>Bold</FontWeight>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Center</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox335</rd:DefaultName>
          <Top>0.03175cm</Top>
          <Left>8.38624cm</Left>
          <Height>0.57697cm</Height>
          <Width>2.60882cm</Width>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox7">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value />
                  <Style>
                    <FontWeight>Bold</FontWeight>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox4</rd:DefaultName>
          <Top>0.03175cm</Top>
          <Left>4.65032cm</Left>
          <Height>0.57697cm</Height>
          <Width>3.73592cm</Width>
          <ZIndex>1</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <BottomBorder>
              <Color>Black</Color>
              <Style>Solid</Style>
              <Width>1pt</Width>
            </BottomBorder>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox8">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>Confirmed by (Employee):</Value>
                  <Style>
                    <FontWeight>Bold</FontWeight>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox4</rd:DefaultName>
          <Top>0.03175cm</Top>
          <Left>10.99505cm</Left>
          <Height>0.57697cm</Height>
          <Width>5.48948cm</Width>
          <ZIndex>2</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox9">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value>Prepared by (MIS Staff):</Value>
                  <Style>
                    <FontWeight>Bold</FontWeight>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox4</rd:DefaultName>
          <Top>0.03175cm</Top>
          <Left>0.23152cm</Left>
          <Height>0.57697cm</Height>
          <Width>4.4188cm</Width>
          <ZIndex>3</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
        <Textbox Name="Textbox10">
          <CanGrow>true</CanGrow>
          <KeepTogether>true</KeepTogether>
          <Paragraphs>
            <Paragraph>
              <TextRuns>
                <TextRun>
                  <Value />
                  <Style>
                    <FontWeight>Bold</FontWeight>
                  </Style>
                </TextRun>
              </TextRuns>
              <Style>
                <TextAlign>Left</TextAlign>
              </Style>
            </Paragraph>
          </Paragraphs>
          <rd:DefaultName>Textbox4</rd:DefaultName>
          <Top>0.03175cm</Top>
          <Left>16.48453cm</Left>
          <Height>0.57697cm</Height>
          <Width>3.59482cm</Width>
          <ZIndex>4</ZIndex>
          <Style>
            <Border>
              <Style>None</Style>
            </Border>
            <BottomBorder>
              <Color>Black</Color>
              <Style>Solid</Style>
              <Width>1pt</Width>
            </BottomBorder>
            <PaddingLeft>2pt</PaddingLeft>
            <PaddingRight>2pt</PaddingRight>
            <PaddingTop>2pt</PaddingTop>
            <PaddingBottom>2pt</PaddingBottom>
          </Style>
        </Textbox>
      </ReportItems>
      <Style>
        <Border>
          <Style>None</Style>
        </Border>
      </Style>
    </PageFooter>
    <PageHeight>29.7cm</PageHeight>
    <PageWidth>21cm</PageWidth>
    <LeftMargin>0cm</LeftMargin>
    <RightMargin>0cm</RightMargin>
    <TopMargin>0cm</TopMargin>
    <BottomMargin>0cm</BottomMargin>
    <ColumnSpacing>0.13cm</ColumnSpacing>
    <Style>
      <BackgroundImage>
        <Source>Embedded</Source>
        <Value>=Switch(Parameters!bk.Value = "Original","",Parameters!bk.Value = "Copy","",Parameters!bk.Value = "","")</Value>
        <BackgroundRepeat>RepeatY</BackgroundRepeat>
      </BackgroundImage>
    </Style>
  </Page>
  <EmbeddedImages>
    <EmbeddedImage Name="logo">
      <MIMEType>image/png</MIMEType>
      <ImageData>iVBORw0KGgoAAAANSUhEUgAAAKgAAACwCAIAAAAUrLIVAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAvDSURBVHhe7Z09i1xHFob9pzbb/2DY3zD5RhNtKIxjy/EETgwODAqcKBIYJVJikCObjVYoEUigxHamfXAVTfP26Tv1capudfd5eVm8M7eqzj1Pfd7bmv7ic+gmFeBvVFcI/u37d7/977/PX7/48eef8P3Dk4P/8Z9/ffHvfx7M/z3+7XfPf+B6ClKcSnJ1V6qLB//h08dffv8VYF99/83d0/tjrv3+8us7OgSV0wQN5SavQhcJHgaMS0gDRlANNTMEjdL0FcwHlwSeYffts4fJsM+ZTkAwL9+8+uOvP3N8F6ULAE9yGWeS96VMeBfXA9YFzw6LISXbscVNwExL+QbW1nLgGTcsoovM520mePaDi08AC4Fny8aB6rKG+LaZAJY9CywBnuyQI8na1ZhbW/AUsDP460Z+bDaAS43+3cCzBDKxS3au3utM/vuAZ/t2TWt5lblxtn45EftpNngOae4PVi/R7PxJRU7KHpoH/jbn9m2z8O916psEnt590UfzcWbm3+WZzwzwOw709L5VfmiaBajwyhFm0zd56I8Fz/l15oqeXqG+fPNKlk+5zPRxEf6bSqiKCqdtQpkRZx73B4Ind6OzRv0l70mllOmNrRaVcy8MygmdgHvJrQ7WKPBDp3cGB/VvoBJJcdOFtdEJaHroNDZn2vcHT9CDFksGHElvmA+lHtPl3Sgp9YBBO1Y61mj2zuBJx4jRQE9iss1t1EtqM10L/iD25CM+LkAvb+ji5fIET6Duq6DLM06p03Qz+KT00sH39qmtM6oNuYEnRN/bdkGeJDWbdkkx8zNnAd889Ex1G/IBT3ASbo8dkSdJ/aYdx1bCL/X3eAR7B/CO1FnLR7y8klZMu0+q3Ijj2u/Ovhe8F3W2x+Oe
XEpbpgetplTrtfP3Zd8FHlQSXJs5Fw09vUhzpgeBT/Ka+R3Zt4N32cMzGoZmPEkaNT06DK+Drhf7RvAu1Ke9lJR2TU/of9wsc5u0W2vS7nK+bwHPDXSuW0TvvlvZkLRuegL4JNbHzjFD8f4tcAv4zimLTuPSZ8slAZieBh71T/v9z3SrwXPIliCq3B9xgyQG0zPBI5LQedijeK6rSXXgOw9vdJpc0VxJGKYng0/qHEUcFnJF9aoAzwQlDVd5L+pIIjG9C3j0/PULiaTKzWGXgu/c0LGbzRXtIQnG9F7gUc88ykavbeksBd+zIM3cwJuSeEzvCB71sL9/eJJrqVER+J4ndNM+S7QhCcn0vuBRD/uGJD8Onpmk+dy547p+LInK9O7gUQ/72hPy4+CbJ/lFqCMJzPQK4FHzPr92wn8EfPMk37bwDJLEZnoR8KiZfdWEvwW+eZLf5SnNhiQ80+uAJ3Vtz/WqHuVugW97o0Dzk5/IPiqJ0PQ64FHzkCtfXs+Cp+9IpYUe93mKZkmEppcCj4hHIix04Y2cBc8iLTWWeN8HNeckQZpeDTxq+/hG4e7KBt/W3ViZcvnFJHGaXhA8aht+JU/MbPDM8ySi1rUviSVc01Sbr+6Q1Gl6zYZY7FNuq1wCYmtzN1qSEdPcRr66Q1Kn6ctqqF8BPjvAz5NkxHSAH6QAnx3g50kyYjrAD1KAzw7w8yQZMR3gBynAZwf4eZKMmA7wgxTgswP8PElGTAf4QQrw2QF+niQjpgP8IAX47AA/T5IR0wF+kAJ8doCfJ8mI6QA/SAE+O8DPk2TEdIAfpACfHeDnSTJiOsAPUoDPDvDzJBkxHeAHKcBnB/h5koyYDvCDFOCzA/w8SUZMB/hBCvDZAX6eJCOmA/wgBfjsAD9PkhHTAX6QAnz2rYP/7vkP939/9fYES0ZM3/397d6dljpNX1ZDJd7+szQKngISaPhCDcoM1VKAv1oH+Bt1gL9RB/gbdYC/UQf4G3WA
v1EH+Bt1gL9RB/gbdR34l29e/fjzT3MsgZr+9tmDlNpw55d2nvru6b00sW0pbrrqjnq8/TesFfxMSUZMl7/LeuvxzeanLvkT4AdJWdPxWtYzTYOoJ5ezl4KmA7xbmoZSTy5kL6VMB3ifNE2gnlzCXoqYDvAOaZpGPflR9nK96QDfm6bJ1JO32cvFpgN8V5p2oZ68wV6uNB3g29O0I/Xkc+zlMtMBvjFNu1NPNtnLNaYDfEuaFqGefMpeLjAd4KvT1EYdPPIT023f4Szs5bemA3xdmpqplzdU2EXEx+zlV6YDfEWaeqhXNdTJXn5uOsCXpqmTOpJfmT7w6GEvPzQd4IvS9Pz1i07qSH5r+phHM3v5iekAX8SjwUIdyQWmhUcb+xIH+CHgT6kjucb0KY9B7AO8P3iTOpLLTJs8RrAP8M7gz1FHcqXpczzc2Qd4T/Ab1JFcbHqDhy/7AO8Gfps6kutNb/NwZB/gfcA/Sh1JEdOP8vBiH+AdwJdQR1LKdAkPF/YBvhd8IXUkBU0X8uhnH+C7wJdTR1LWdDmPTvYBvh18FXUkxU1X8ehhH+AbwddSR1KD6VoezewDfAv4BupIKjHdwKONfYCvBt9GHUk9ptt4NLAP8HXgm6kjqcp0M49a9gG+AnwPdSS1me7hUcU+wJeC76SOpELTnTzK2S8NnuDkX9mX+Jfff83ly3R/8nd3T91PHUnqTffzIFQJ3vTb9+9ygQJxsSS5xCX3YoP/8OljwweeKELBXMVKkjhNLzIQj/XHX382UMAlFM5O9XQcqa7Ed0/vc/mVJEGaXhA804MEWeJvnz3k8ps6C57u9uXXd1JpiQsbnimJ0PRq4NsGHjME4HIVm9ra3FVtVo/tsjA7SsIzvRR4gpHwCk13yVU8pi3wqG22wVVbmNGS2EyvA77t3xHgqnX2EfBsE6T2Qi+10ZPYTC8CnokafhJboatu4RHwqG2xwdxA4XozWhKY6RXA91Df/gaaUz0OHjVH
swh7icr0CuCbF1a24bV5LgLfvOrgFdhLSKZ3B9/277STG4IvAo+ev34hjZV7d/YSj+l9wfdQL9/JH6sUPOr5S7H7spdgTO8FnrQ0z/CYxOaKKlUBnhDbHukk78heIjG9C3gSQlokknL3HJ0qwKOexR5TdpfzvYRhej54mPVQxz0x14FHzY/zkmFf+xKvXxKD6cngO4cQZteV62pSNXjEkVGCqHXbfqRZ0rrpmeB7dsrJ/S9EWsCjnl1oMjuaaUu+NG16DnhuuT91zRu6YzWC79yVJDPXzUm3tGt6QiRM7z2742SvPXIjeOTCHrNwjB760qLp0eCbn3wfu+EJ3Tm1g0de7LmfoXmX5kyPC4CaXbLkeybqAo+82OOvvv9m0As9acj0CPAkp38jnOx+Eu4FjxzZc3tMiV6z2UHSiml38G1/qM20O3XkAB45ssfM/L6f4ZH6TTuCJ/j+TdzBI6gjH/DIlz12xC81m3YB74sck1L3+S/JDTwiRPev/EuTf+faL3Wa7gHPjROkL3I8jjryBJ/U/4DCNNU2P+uVqky3gafUuPsdRx35g0edz/M3zKhin1y75kklpqvAEwBhuA/xgyc80h4CHpFHrz2t6dQDCucAKWu6BDzXDOWNSdqcl1ijwCNmKt/t3jnfPzxhiJCvc3OjXG/aBE+F/JzKez4rUW7SNWIDb2og+CSyJrc31AzH1A84RsMs5VGuMZ0u5n8pmEgPHdmnZi4ZuqiLhoNHZHNyEi/L06b3Y80Aj+jL9Gi54TDmADxzoB80CXxSDP1j7zLQD5oKHtG7J6/6a3ryin6q2eCTPnz66P6M71LMtnHa1n1D+4BPYuafc0xaxCxz3HK++b21J/ikW8APct/3jf3aH3zSteK/e3q/GvKkVcAngX/QO4/5ZhOzzsR+qrXAJ7H1Y+d/oQc/Dmns2Ad9hsxRK4I/iGMuE8DQlz2OZojveC6v1dLgkzjvskwu2wPgTXj7HsobdAHgj8WqyUQ6
56XfhlmGCOOCxvepLgz8QYww8k72p50FaCjBXn/9LtGlghe9ff8OJGwJmXhdugKVUBUVMo2v8KDNXVcC3lR6v47TK/ZtpytxLnztumbwoQ0F+BtVgL9RBfgbVYC/SX3+/H++wKgIoisNLgAAAABJRU5ErkJggg==</ImageData>
    </EmbeddedImage>
  </EmbeddedImages>
  <rd:ReportID>d6c01e99-a099-47e6-a5f2-90eb9c9cb087</rd:ReportID>
  <rd:ReportUnitType>Cm</rd:ReportUnitType>
</Report>'
insert into dbo.rtemplate(Id,tdoctype,tdesc,[version],tempxml)
--values('5','360Data','user_softs_other',5,@xmldoc)
--values('4','360Data','user_hw_softs',4,@xmldoc)
values('6','MISPC','wwts-pc-controll',6,@xmldoc)
--delete from rtemplate where version = 6
-- select max(id) from rtemplate
-- select * from rtemplate