//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsWeb.Service99 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service99.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTable_n", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTable_n(string inSystem, string inTable, string inWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSetTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetSetTable(string inSystem, string inTable, string inWhere, string inXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTable(string inSystem, string inTable, string inWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSQLTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSQLTable(string inSystem, string inDB, string inUser, string inTable, string inWhere);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ReportsWeb.Service99.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ReportsWeb.Service99.ServiceSoap>, ReportsWeb.Service99.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetTable_n(string inSystem, string inTable, string inWhere) {
            return base.Channel.GetTable_n(inSystem, inTable, inWhere);
        }
        
        public void GetSetTable(string inSystem, string inTable, string inWhere, string inXML) {
            base.Channel.GetSetTable(inSystem, inTable, inWhere, inXML);
        }
        
        public string GetTable(string inSystem, string inTable, string inWhere) {
            return base.Channel.GetTable(inSystem, inTable, inWhere);
        }
        
        public System.Data.DataSet GetSQLTable(string inSystem, string inDB, string inUser, string inTable, string inWhere) {
            return base.Channel.GetSQLTable(inSystem, inDB, inUser, inTable, inWhere);
        }
    }
}
